Repository py-pdf/pypdf_table_extraction, pull requests merged in 2024-10, with the labels that each got.

#153 [IMP] Improve poppler subprocess security
  camelot/backends/poppler_backend.py
Labels: bug

#157 [IMP] Versioning, centralize metadata, Flake8 fixes
  camelot/__init__.py
  camelot/__version__.py
  pyproject.toml
  tests/test_common.py
Labels: build, refactoring

#158 Rebrand CLI to pypdf_table_extraction
  camelot/cli.py
  docs/user/advanced.rst
  docs/user/cli.rst
  docs/user/quickstart.rst
Labels: documentation, enhancement

#94 Speedup as in https://github.com/camelot-dev/camelot/issues/161
  camelot/core.py
Labels: performance

#52 Refactor method `Table.set_edges` for readability
  camelot/core.py
Labels: refactoring, style

#154 Various fixes
  camelot/core.py
Labels: bug, style

#12 Add typing for camelot/backends
  camelot/backends/base.py
  camelot/backends/ghostscript_backend.py
  camelot/backends/image_conversion.py
  camelot/backends/poppler_backend.py
Labels: enhancement

#184 Fix Flake8 warning on test_invalid_url
  tests/test_errors.py
Labels: refactoring

#166 [REF] slow np.isclose to math.isclose
  camelot/parsers/base.py
  camelot/utils.py
Labels: performance, refactoring

#182 [IMP] CLI Documentation
  camelot/cli.py
Labels: documentation

#167 New test for matplotlib importerror
  tests/test_cli.py
Labels: testing

#185 Pre-commit fixes
  tests/test_cli.py
Labels: style

#187 [REF] silence download_url S310,add typing
  camelot/utils.py
Labels: refactoring, testing

#189 [FIX] Warning on test cli quiet
  tests/test_cli.py
Labels: testing

#178 [REF] split_textline
  camelot/utils.py
Labels: refactoring

#175 [REF] get_index_closest_point
  camelot/utils.py
Labels: refactoring

#195 [REF] Scale Image
  camelot/utils.py
Labels: refactoring

#201 [REF] Fix B028
  camelot/parsers/stream.py
Labels: refactoring

#197 [REF] lattice -reduce_index
  camelot/parsers/lattice.py
Labels: refactoring

#198 [REF] copy spanning text
  camelot/core.py
Labels: refactoring

#200 [REF]: get_table_index
  camelot/utils.py
Labels: refactoring

#202 [REF]: Find_closest_tls
  camelot/parsers/network.py
Labels: refactoring

#199 [REF]: get_table_areas
  camelot/core.py
Labels: refactoring

#203 [REF] search_table_body
  camelot/parsers/network.py
Labels: refactoring

#205 Flake8 fixes base parser
  camelot/parsers/base.py
Labels: refactoring

#204 [REF]: find lines
  camelot/image_processing.py
Labels: refactoring

#216 [REF] Network parser search header split into sub methods to reduce complexity
  camelot/parsers/network.py
Labels: refactoring

#211 [REF]: network parser generate_table_bbox -> split into mark_processe…
  camelot/parsers/network.py
Labels: refactoring

#221 Updated pypdf dependency to include v5
  poetry.lock
  pyproject.toml
Labels: dependencies

#217 Network parser Fix B903
  camelot/parsers/network.py
Labels: python

#223 [REF]: Core Table set edges to reduce complexity
  camelot/core.py
Labels: bug, refactoring

#228 Activate pre-commit on gh actions
  .github/workflows/tests.yml
Labels: github_actions, testing

#233 boundaries to split lines Fix index out of range
  camelot/utils.py
Labels: bug

#229 Update docstrings, add backends and fallback
  camelot/io.py
  camelot/parsers/lattice.py
Labels: documentation, python

#244 [REF] netw gen bbox
  camelot/parsers/network.py
Labels: bug, performance, refactoring

#247 [REF]: core set_border: Improve performance, Fix index out of Range
  camelot/core.py
Labels: bug, performance

#249 [FIX] compute_parse_error, Index out of range
  camelot/parsers/base.py
Labels: bug

#242 [REF] remove_unconnected_edges
  camelot/parsers/network.py
Labels: performance, refactoring

#243 [REF] Compute_plausible_gaps, Efficiency, Stability
  camelot/parsers/network.py
Labels: performance, refactoring
